name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]  # Updated to Node 20 (LTS)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to v4

    - name: Setup Node.js
      uses: actions/setup-node@v4  # Updated to v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install system dependencies for Puppeteer
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgbm-dev \
          libnss3 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libdrm-dev \
          libxkbcommon-dev \
          libxcomposite-dev \
          libxdamage-dev \
          libxrandr-dev \
          libgtk-3-dev \
          libasound2-dev \
          xvfb

    - name: Install npm dependencies
      run: |
        npm install
        npm ci

    - name: Verify Puppeteer
      run: |
        node -e "require('puppeteer').launch().then(async browser => { 
          const page = await browser.newPage(); 
          await page.close(); 
          await browser.close(); 
        })"

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Build project
      run: npm run build --if-present

    - name: Upload artifacts
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: build-artifacts
        path: |
          public/
          server/
          package*.json
        retention-days: 1
