name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies (generate package-lock.json)
      run: npm install

    - name: Clean install dependencies
      run: npm ci

    - name: Install Puppeteer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev wget xvfb
        
    - name: Run tests (if you have any)
      run: npm test
      env:
        CI: true

    - name: Build project (if needed)
      run: npm run build --if-present

    - name: Verify Puppeteer can launch
      run: |
        node -e "require('puppeteer').launch().then(b => b.close())"
        
    - name: Upload build artifacts (if needed)
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: build-artifacts
        path: |
          public/
          server/
        retention-days: 1
