name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        
    - name: Install dependencies
      run: |
        # Create minimal package.json if missing
        if [ ! -f package.json ]; then
          echo '{"dependencies":{"puppeteer":"^21.6.0"}}' > package.json
        fi
        
        # Install without requiring lockfile
        npm install
        
    - name: Verify Puppeteer
      run: |
        node -e "
          require('puppeteer').launch({headless: true})
            .then(b => b.close())
            .catch(e => { console.error(e); process.exit(1); })
        "
